# coding: utf-8

"""
    aind-service-template

     ## aind-service-template  Service to pull data from example backend.  

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from orcid_service_client.api.healthcheck_api import HealthcheckApi


class TestHealthcheckApi(unittest.TestCase):
    """HealthcheckApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthcheckApi()

    def tearDown(self) -> None:
        pass

    def test_get_health_healthcheck_get(self) -> None:
        """Test case for get_health_healthcheck_get

        Perform a Health Check
        """
        pass


if __name__ == '__main__':
    unittest.main()
