# coding: utf-8

"""
    orcid-service

     ## orcid-service  Service to resolve researcher names to ORCID iDs using the public ORCID registry.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from orcid_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_orcid(self) -> None:
        """Test case for get_orcid

        Get Orcid
        """
        pass


if __name__ == '__main__':
    unittest.main()
