# coding: utf-8

# flake8: noqa
"""
    orcid-service

     ## orcid-service  Service to resolve researcher names to ORCID iDs using the public ORCID registry.  

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from orcid_service_async_client.models.http_validation_error import HTTPValidationError
from orcid_service_async_client.models.health_check import HealthCheck
from orcid_service_async_client.models.orcid_id import OrcidId
from orcid_service_async_client.models.validation_error import ValidationError
from orcid_service_async_client.models.validation_error_loc_inner import ValidationErrorLocInner
