# coding: utf-8

"""
    aind-service-template

     ## aind-service-template  Service to pull data from example backend.  

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from orcid_service_async_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.IsolatedAsyncioTestCase):
    """DefaultApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DefaultApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_content_example_arg_get(self) -> None:
        """Test case for get_content_example_arg_get

        Get Content
        """
        pass


if __name__ == '__main__':
    unittest.main()
